CREATE DATABASE /*!32312 IF NOT EXISTS*/ `my_cv_db` /*!40100 DEFAULT CHARACTER SET latin1 */;
GRANT ALL PRIVILEGES ON my_cv_db.* TO 'my_cv_user'@'%' IDENTIFIED BY 'my-secret-pw' WITH GRANT OPTION;
FLUSH PRIVILEGES;
